#!/usr/bin/bash

#git-create-version-tag <tag-name> <maven-module>
#git-create-version-tag r4m-sources sources

TAG=$1/v$(mvn org.apache.maven.plugins:maven-help-plugin:evaluate -Dexpression=project.version -q -DforceStdout -pl=$2)
# delete local tag in case it remained from a previous one!
git tag -d $TAG &>/dev/null
mvn org.apache.maven.plugins:maven-scm-plugin:tag -Dtag=$TAG -DpushChanges=false -q
printf $TAG

