#!/usr/bin/bash

if TAG=$(git describe --tags --abbrev=0 remotes/origin/master --match $2'/v*' 2>/dev/null)
then
  if git diff --quiet HEAD $TAG -- $1
  then
    printf 0;
  else
    printf 1;
  fi
else
  printf 1;
fi

