#!/usr/bin/bash

#git-create-version-tag <tag-name> <maven-module>
#git-create-version-tag r4m-sources sources

TAG=$1/v$(mvn org.apache.maven.plugins:maven-help-plugin:evaluate -Dexpression=project.version -q -DforceStdout -pl $2)
mvn org.apache.maven.plugins:maven-scm-plugin:tag -Dtag=$TAG -Dsign=true -DpushChanges=false -q
printf $TAG

