#!/usr/bin/bash

#git-check-version-tag <tag-name> <maven-module>
#git-check-version-tag r4m-sources sources

TAG=$1/v$(mvn $GLOBAL_SETTINGS_FILE $SETTINGS_FILE org.apache.maven.plugins:maven-help-plugin:evaluate -Dexpression=project.version -q -DforceStdout -pl=$2)
if git ls-remote --tags --exit-code origin refs/tags/$TAG &>/dev/null
then
  printf 0;
else
  printf 1;
fi

